package com.nengliang.web.entity;

import java.util.Date;

public class WeatherId {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.today_fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private String today_fa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.today_fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private String today_fb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.future_fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private String future_fa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.future_fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private String future_fb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private String fa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private String fb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.create_time
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_id.update_time
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.id
     *
     * @return the value of weather_id.id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.id
     *
     * @param id the value for weather_id.id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.today_fa
     *
     * @return the value of weather_id.today_fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public String getToday_fa() {
        return today_fa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.today_fa
     *
     * @param today_fa the value for weather_id.today_fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setToday_fa(String today_fa) {
        this.today_fa = today_fa == null ? null : today_fa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.today_fb
     *
     * @return the value of weather_id.today_fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public String getToday_fb() {
        return today_fb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.today_fb
     *
     * @param today_fb the value for weather_id.today_fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setToday_fb(String today_fb) {
        this.today_fb = today_fb == null ? null : today_fb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.future_fa
     *
     * @return the value of weather_id.future_fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public String getFuture_fa() {
        return future_fa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.future_fa
     *
     * @param future_fa the value for weather_id.future_fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setFuture_fa(String future_fa) {
        this.future_fa = future_fa == null ? null : future_fa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.future_fb
     *
     * @return the value of weather_id.future_fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public String getFuture_fb() {
        return future_fb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.future_fb
     *
     * @param future_fb the value for weather_id.future_fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setFuture_fb(String future_fb) {
        this.future_fb = future_fb == null ? null : future_fb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.fa
     *
     * @return the value of weather_id.fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public String getFa() {
        return fa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.fa
     *
     * @param fa the value for weather_id.fa
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setFa(String fa) {
        this.fa = fa == null ? null : fa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.fb
     *
     * @return the value of weather_id.fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public String getFb() {
        return fb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.fb
     *
     * @param fb the value for weather_id.fb
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setFb(String fb) {
        this.fb = fb == null ? null : fb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.create_time
     *
     * @return the value of weather_id.create_time
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.create_time
     *
     * @param create_time the value for weather_id.create_time
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_id.update_time
     *
     * @return the value of weather_id.update_time
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_id.update_time
     *
     * @param update_time the value for weather_id.update_time
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}