package com.nengliang.web.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeatherTodayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public WeatherTodayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andToday_idIsNull() {
            addCriterion("today_id is null");
            return (Criteria) this;
        }

        public Criteria andToday_idIsNotNull() {
            addCriterion("today_id is not null");
            return (Criteria) this;
        }

        public Criteria andToday_idEqualTo(Integer value) {
            addCriterion("today_id =", value, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idNotEqualTo(Integer value) {
            addCriterion("today_id <>", value, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idGreaterThan(Integer value) {
            addCriterion("today_id >", value, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("today_id >=", value, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idLessThan(Integer value) {
            addCriterion("today_id <", value, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idLessThanOrEqualTo(Integer value) {
            addCriterion("today_id <=", value, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idIn(List<Integer> values) {
            addCriterion("today_id in", values, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idNotIn(List<Integer> values) {
            addCriterion("today_id not in", values, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idBetween(Integer value1, Integer value2) {
            addCriterion("today_id between", value1, value2, "today_id");
            return (Criteria) this;
        }

        public Criteria andToday_idNotBetween(Integer value1, Integer value2) {
            addCriterion("today_id not between", value1, value2, "today_id");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andDate_yIsNull() {
            addCriterion("date_y is null");
            return (Criteria) this;
        }

        public Criteria andDate_yIsNotNull() {
            addCriterion("date_y is not null");
            return (Criteria) this;
        }

        public Criteria andDate_yEqualTo(String value) {
            addCriterion("date_y =", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yNotEqualTo(String value) {
            addCriterion("date_y <>", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yGreaterThan(String value) {
            addCriterion("date_y >", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yGreaterThanOrEqualTo(String value) {
            addCriterion("date_y >=", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yLessThan(String value) {
            addCriterion("date_y <", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yLessThanOrEqualTo(String value) {
            addCriterion("date_y <=", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yLike(String value) {
            addCriterion("date_y like", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yNotLike(String value) {
            addCriterion("date_y not like", value, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yIn(List<String> values) {
            addCriterion("date_y in", values, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yNotIn(List<String> values) {
            addCriterion("date_y not in", values, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yBetween(String value1, String value2) {
            addCriterion("date_y between", value1, value2, "date_y");
            return (Criteria) this;
        }

        public Criteria andDate_yNotBetween(String value1, String value2) {
            addCriterion("date_y not between", value1, value2, "date_y");
            return (Criteria) this;
        }

        public Criteria andWeekIsNull() {
            addCriterion("week is null");
            return (Criteria) this;
        }

        public Criteria andWeekIsNotNull() {
            addCriterion("week is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEqualTo(String value) {
            addCriterion("week =", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotEqualTo(String value) {
            addCriterion("week <>", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThan(String value) {
            addCriterion("week >", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThanOrEqualTo(String value) {
            addCriterion("week >=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThan(String value) {
            addCriterion("week <", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThanOrEqualTo(String value) {
            addCriterion("week <=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLike(String value) {
            addCriterion("week like", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotLike(String value) {
            addCriterion("week not like", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekIn(List<String> values) {
            addCriterion("week in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotIn(List<String> values) {
            addCriterion("week not in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekBetween(String value1, String value2) {
            addCriterion("week between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotBetween(String value1, String value2) {
            addCriterion("week not between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNull() {
            addCriterion("temperature is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNotNull() {
            addCriterion("temperature is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureEqualTo(String value) {
            addCriterion("temperature =", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotEqualTo(String value) {
            addCriterion("temperature <>", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThan(String value) {
            addCriterion("temperature >", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("temperature >=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThan(String value) {
            addCriterion("temperature <", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThanOrEqualTo(String value) {
            addCriterion("temperature <=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLike(String value) {
            addCriterion("temperature like", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotLike(String value) {
            addCriterion("temperature not like", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureIn(List<String> values) {
            addCriterion("temperature in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotIn(List<String> values) {
            addCriterion("temperature not in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureBetween(String value1, String value2) {
            addCriterion("temperature between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotBetween(String value1, String value2) {
            addCriterion("temperature not between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andWeatherIsNull() {
            addCriterion("weather is null");
            return (Criteria) this;
        }

        public Criteria andWeatherIsNotNull() {
            addCriterion("weather is not null");
            return (Criteria) this;
        }

        public Criteria andWeatherEqualTo(String value) {
            addCriterion("weather =", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotEqualTo(String value) {
            addCriterion("weather <>", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherGreaterThan(String value) {
            addCriterion("weather >", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherGreaterThanOrEqualTo(String value) {
            addCriterion("weather >=", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherLessThan(String value) {
            addCriterion("weather <", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherLessThanOrEqualTo(String value) {
            addCriterion("weather <=", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherLike(String value) {
            addCriterion("weather like", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotLike(String value) {
            addCriterion("weather not like", value, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherIn(List<String> values) {
            addCriterion("weather in", values, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotIn(List<String> values) {
            addCriterion("weather not in", values, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherBetween(String value1, String value2) {
            addCriterion("weather between", value1, value2, "weather");
            return (Criteria) this;
        }

        public Criteria andWeatherNotBetween(String value1, String value2) {
            addCriterion("weather not between", value1, value2, "weather");
            return (Criteria) this;
        }

        public Criteria andWindIsNull() {
            addCriterion("wind is null");
            return (Criteria) this;
        }

        public Criteria andWindIsNotNull() {
            addCriterion("wind is not null");
            return (Criteria) this;
        }

        public Criteria andWindEqualTo(String value) {
            addCriterion("wind =", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindNotEqualTo(String value) {
            addCriterion("wind <>", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindGreaterThan(String value) {
            addCriterion("wind >", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindGreaterThanOrEqualTo(String value) {
            addCriterion("wind >=", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindLessThan(String value) {
            addCriterion("wind <", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindLessThanOrEqualTo(String value) {
            addCriterion("wind <=", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindLike(String value) {
            addCriterion("wind like", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindNotLike(String value) {
            addCriterion("wind not like", value, "wind");
            return (Criteria) this;
        }

        public Criteria andWindIn(List<String> values) {
            addCriterion("wind in", values, "wind");
            return (Criteria) this;
        }

        public Criteria andWindNotIn(List<String> values) {
            addCriterion("wind not in", values, "wind");
            return (Criteria) this;
        }

        public Criteria andWindBetween(String value1, String value2) {
            addCriterion("wind between", value1, value2, "wind");
            return (Criteria) this;
        }

        public Criteria andWindNotBetween(String value1, String value2) {
            addCriterion("wind not between", value1, value2, "wind");
            return (Criteria) this;
        }

        public Criteria andDressing_indexIsNull() {
            addCriterion("dressing_index is null");
            return (Criteria) this;
        }

        public Criteria andDressing_indexIsNotNull() {
            addCriterion("dressing_index is not null");
            return (Criteria) this;
        }

        public Criteria andDressing_indexEqualTo(String value) {
            addCriterion("dressing_index =", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexNotEqualTo(String value) {
            addCriterion("dressing_index <>", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexGreaterThan(String value) {
            addCriterion("dressing_index >", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexGreaterThanOrEqualTo(String value) {
            addCriterion("dressing_index >=", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexLessThan(String value) {
            addCriterion("dressing_index <", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexLessThanOrEqualTo(String value) {
            addCriterion("dressing_index <=", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexLike(String value) {
            addCriterion("dressing_index like", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexNotLike(String value) {
            addCriterion("dressing_index not like", value, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexIn(List<String> values) {
            addCriterion("dressing_index in", values, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexNotIn(List<String> values) {
            addCriterion("dressing_index not in", values, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexBetween(String value1, String value2) {
            addCriterion("dressing_index between", value1, value2, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_indexNotBetween(String value1, String value2) {
            addCriterion("dressing_index not between", value1, value2, "dressing_index");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceIsNull() {
            addCriterion("dressing_advice is null");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceIsNotNull() {
            addCriterion("dressing_advice is not null");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceEqualTo(String value) {
            addCriterion("dressing_advice =", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceNotEqualTo(String value) {
            addCriterion("dressing_advice <>", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceGreaterThan(String value) {
            addCriterion("dressing_advice >", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceGreaterThanOrEqualTo(String value) {
            addCriterion("dressing_advice >=", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceLessThan(String value) {
            addCriterion("dressing_advice <", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceLessThanOrEqualTo(String value) {
            addCriterion("dressing_advice <=", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceLike(String value) {
            addCriterion("dressing_advice like", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceNotLike(String value) {
            addCriterion("dressing_advice not like", value, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceIn(List<String> values) {
            addCriterion("dressing_advice in", values, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceNotIn(List<String> values) {
            addCriterion("dressing_advice not in", values, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceBetween(String value1, String value2) {
            addCriterion("dressing_advice between", value1, value2, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andDressing_adviceNotBetween(String value1, String value2) {
            addCriterion("dressing_advice not between", value1, value2, "dressing_advice");
            return (Criteria) this;
        }

        public Criteria andUv_indexIsNull() {
            addCriterion("uv_index is null");
            return (Criteria) this;
        }

        public Criteria andUv_indexIsNotNull() {
            addCriterion("uv_index is not null");
            return (Criteria) this;
        }

        public Criteria andUv_indexEqualTo(String value) {
            addCriterion("uv_index =", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexNotEqualTo(String value) {
            addCriterion("uv_index <>", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexGreaterThan(String value) {
            addCriterion("uv_index >", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexGreaterThanOrEqualTo(String value) {
            addCriterion("uv_index >=", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexLessThan(String value) {
            addCriterion("uv_index <", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexLessThanOrEqualTo(String value) {
            addCriterion("uv_index <=", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexLike(String value) {
            addCriterion("uv_index like", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexNotLike(String value) {
            addCriterion("uv_index not like", value, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexIn(List<String> values) {
            addCriterion("uv_index in", values, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexNotIn(List<String> values) {
            addCriterion("uv_index not in", values, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexBetween(String value1, String value2) {
            addCriterion("uv_index between", value1, value2, "uv_index");
            return (Criteria) this;
        }

        public Criteria andUv_indexNotBetween(String value1, String value2) {
            addCriterion("uv_index not between", value1, value2, "uv_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexIsNull() {
            addCriterion("comfort_index is null");
            return (Criteria) this;
        }

        public Criteria andComfort_indexIsNotNull() {
            addCriterion("comfort_index is not null");
            return (Criteria) this;
        }

        public Criteria andComfort_indexEqualTo(String value) {
            addCriterion("comfort_index =", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexNotEqualTo(String value) {
            addCriterion("comfort_index <>", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexGreaterThan(String value) {
            addCriterion("comfort_index >", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexGreaterThanOrEqualTo(String value) {
            addCriterion("comfort_index >=", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexLessThan(String value) {
            addCriterion("comfort_index <", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexLessThanOrEqualTo(String value) {
            addCriterion("comfort_index <=", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexLike(String value) {
            addCriterion("comfort_index like", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexNotLike(String value) {
            addCriterion("comfort_index not like", value, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexIn(List<String> values) {
            addCriterion("comfort_index in", values, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexNotIn(List<String> values) {
            addCriterion("comfort_index not in", values, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexBetween(String value1, String value2) {
            addCriterion("comfort_index between", value1, value2, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andComfort_indexNotBetween(String value1, String value2) {
            addCriterion("comfort_index not between", value1, value2, "comfort_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexIsNull() {
            addCriterion("wash_index is null");
            return (Criteria) this;
        }

        public Criteria andWash_indexIsNotNull() {
            addCriterion("wash_index is not null");
            return (Criteria) this;
        }

        public Criteria andWash_indexEqualTo(String value) {
            addCriterion("wash_index =", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexNotEqualTo(String value) {
            addCriterion("wash_index <>", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexGreaterThan(String value) {
            addCriterion("wash_index >", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexGreaterThanOrEqualTo(String value) {
            addCriterion("wash_index >=", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexLessThan(String value) {
            addCriterion("wash_index <", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexLessThanOrEqualTo(String value) {
            addCriterion("wash_index <=", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexLike(String value) {
            addCriterion("wash_index like", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexNotLike(String value) {
            addCriterion("wash_index not like", value, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexIn(List<String> values) {
            addCriterion("wash_index in", values, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexNotIn(List<String> values) {
            addCriterion("wash_index not in", values, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexBetween(String value1, String value2) {
            addCriterion("wash_index between", value1, value2, "wash_index");
            return (Criteria) this;
        }

        public Criteria andWash_indexNotBetween(String value1, String value2) {
            addCriterion("wash_index not between", value1, value2, "wash_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexIsNull() {
            addCriterion("travel_index is null");
            return (Criteria) this;
        }

        public Criteria andTravel_indexIsNotNull() {
            addCriterion("travel_index is not null");
            return (Criteria) this;
        }

        public Criteria andTravel_indexEqualTo(String value) {
            addCriterion("travel_index =", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexNotEqualTo(String value) {
            addCriterion("travel_index <>", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexGreaterThan(String value) {
            addCriterion("travel_index >", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexGreaterThanOrEqualTo(String value) {
            addCriterion("travel_index >=", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexLessThan(String value) {
            addCriterion("travel_index <", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexLessThanOrEqualTo(String value) {
            addCriterion("travel_index <=", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexLike(String value) {
            addCriterion("travel_index like", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexNotLike(String value) {
            addCriterion("travel_index not like", value, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexIn(List<String> values) {
            addCriterion("travel_index in", values, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexNotIn(List<String> values) {
            addCriterion("travel_index not in", values, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexBetween(String value1, String value2) {
            addCriterion("travel_index between", value1, value2, "travel_index");
            return (Criteria) this;
        }

        public Criteria andTravel_indexNotBetween(String value1, String value2) {
            addCriterion("travel_index not between", value1, value2, "travel_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexIsNull() {
            addCriterion("exercise_index is null");
            return (Criteria) this;
        }

        public Criteria andExercise_indexIsNotNull() {
            addCriterion("exercise_index is not null");
            return (Criteria) this;
        }

        public Criteria andExercise_indexEqualTo(String value) {
            addCriterion("exercise_index =", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexNotEqualTo(String value) {
            addCriterion("exercise_index <>", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexGreaterThan(String value) {
            addCriterion("exercise_index >", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexGreaterThanOrEqualTo(String value) {
            addCriterion("exercise_index >=", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexLessThan(String value) {
            addCriterion("exercise_index <", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexLessThanOrEqualTo(String value) {
            addCriterion("exercise_index <=", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexLike(String value) {
            addCriterion("exercise_index like", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexNotLike(String value) {
            addCriterion("exercise_index not like", value, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexIn(List<String> values) {
            addCriterion("exercise_index in", values, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexNotIn(List<String> values) {
            addCriterion("exercise_index not in", values, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexBetween(String value1, String value2) {
            addCriterion("exercise_index between", value1, value2, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andExercise_indexNotBetween(String value1, String value2) {
            addCriterion("exercise_index not between", value1, value2, "exercise_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexIsNull() {
            addCriterion("drying_index is null");
            return (Criteria) this;
        }

        public Criteria andDrying_indexIsNotNull() {
            addCriterion("drying_index is not null");
            return (Criteria) this;
        }

        public Criteria andDrying_indexEqualTo(String value) {
            addCriterion("drying_index =", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexNotEqualTo(String value) {
            addCriterion("drying_index <>", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexGreaterThan(String value) {
            addCriterion("drying_index >", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexGreaterThanOrEqualTo(String value) {
            addCriterion("drying_index >=", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexLessThan(String value) {
            addCriterion("drying_index <", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexLessThanOrEqualTo(String value) {
            addCriterion("drying_index <=", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexLike(String value) {
            addCriterion("drying_index like", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexNotLike(String value) {
            addCriterion("drying_index not like", value, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexIn(List<String> values) {
            addCriterion("drying_index in", values, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexNotIn(List<String> values) {
            addCriterion("drying_index not in", values, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexBetween(String value1, String value2) {
            addCriterion("drying_index between", value1, value2, "drying_index");
            return (Criteria) this;
        }

        public Criteria andDrying_indexNotBetween(String value1, String value2) {
            addCriterion("drying_index not between", value1, value2, "drying_index");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_today
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 02 11:46:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}