package com.nengliang.web.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeatherSkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public WeatherSkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSk_idIsNull() {
            addCriterion("sk_id is null");
            return (Criteria) this;
        }

        public Criteria andSk_idIsNotNull() {
            addCriterion("sk_id is not null");
            return (Criteria) this;
        }

        public Criteria andSk_idEqualTo(Integer value) {
            addCriterion("sk_id =", value, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idNotEqualTo(Integer value) {
            addCriterion("sk_id <>", value, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idGreaterThan(Integer value) {
            addCriterion("sk_id >", value, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("sk_id >=", value, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idLessThan(Integer value) {
            addCriterion("sk_id <", value, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idLessThanOrEqualTo(Integer value) {
            addCriterion("sk_id <=", value, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idIn(List<Integer> values) {
            addCriterion("sk_id in", values, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idNotIn(List<Integer> values) {
            addCriterion("sk_id not in", values, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idBetween(Integer value1, Integer value2) {
            addCriterion("sk_id between", value1, value2, "sk_id");
            return (Criteria) this;
        }

        public Criteria andSk_idNotBetween(Integer value1, Integer value2) {
            addCriterion("sk_id not between", value1, value2, "sk_id");
            return (Criteria) this;
        }

        public Criteria andTempIsNull() {
            addCriterion("temp is null");
            return (Criteria) this;
        }

        public Criteria andTempIsNotNull() {
            addCriterion("temp is not null");
            return (Criteria) this;
        }

        public Criteria andTempEqualTo(String value) {
            addCriterion("temp =", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotEqualTo(String value) {
            addCriterion("temp <>", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThan(String value) {
            addCriterion("temp >", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempGreaterThanOrEqualTo(String value) {
            addCriterion("temp >=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThan(String value) {
            addCriterion("temp <", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLessThanOrEqualTo(String value) {
            addCriterion("temp <=", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempLike(String value) {
            addCriterion("temp like", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotLike(String value) {
            addCriterion("temp not like", value, "temp");
            return (Criteria) this;
        }

        public Criteria andTempIn(List<String> values) {
            addCriterion("temp in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotIn(List<String> values) {
            addCriterion("temp not in", values, "temp");
            return (Criteria) this;
        }

        public Criteria andTempBetween(String value1, String value2) {
            addCriterion("temp between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andTempNotBetween(String value1, String value2) {
            addCriterion("temp not between", value1, value2, "temp");
            return (Criteria) this;
        }

        public Criteria andWind_directionIsNull() {
            addCriterion("wind_direction is null");
            return (Criteria) this;
        }

        public Criteria andWind_directionIsNotNull() {
            addCriterion("wind_direction is not null");
            return (Criteria) this;
        }

        public Criteria andWind_directionEqualTo(String value) {
            addCriterion("wind_direction =", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionNotEqualTo(String value) {
            addCriterion("wind_direction <>", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionGreaterThan(String value) {
            addCriterion("wind_direction >", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionGreaterThanOrEqualTo(String value) {
            addCriterion("wind_direction >=", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionLessThan(String value) {
            addCriterion("wind_direction <", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionLessThanOrEqualTo(String value) {
            addCriterion("wind_direction <=", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionLike(String value) {
            addCriterion("wind_direction like", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionNotLike(String value) {
            addCriterion("wind_direction not like", value, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionIn(List<String> values) {
            addCriterion("wind_direction in", values, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionNotIn(List<String> values) {
            addCriterion("wind_direction not in", values, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionBetween(String value1, String value2) {
            addCriterion("wind_direction between", value1, value2, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_directionNotBetween(String value1, String value2) {
            addCriterion("wind_direction not between", value1, value2, "wind_direction");
            return (Criteria) this;
        }

        public Criteria andWind_strengthIsNull() {
            addCriterion("wind_strength is null");
            return (Criteria) this;
        }

        public Criteria andWind_strengthIsNotNull() {
            addCriterion("wind_strength is not null");
            return (Criteria) this;
        }

        public Criteria andWind_strengthEqualTo(String value) {
            addCriterion("wind_strength =", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthNotEqualTo(String value) {
            addCriterion("wind_strength <>", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthGreaterThan(String value) {
            addCriterion("wind_strength >", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthGreaterThanOrEqualTo(String value) {
            addCriterion("wind_strength >=", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthLessThan(String value) {
            addCriterion("wind_strength <", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthLessThanOrEqualTo(String value) {
            addCriterion("wind_strength <=", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthLike(String value) {
            addCriterion("wind_strength like", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthNotLike(String value) {
            addCriterion("wind_strength not like", value, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthIn(List<String> values) {
            addCriterion("wind_strength in", values, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthNotIn(List<String> values) {
            addCriterion("wind_strength not in", values, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthBetween(String value1, String value2) {
            addCriterion("wind_strength between", value1, value2, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andWind_strengthNotBetween(String value1, String value2) {
            addCriterion("wind_strength not between", value1, value2, "wind_strength");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNull() {
            addCriterion("humidity is null");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNotNull() {
            addCriterion("humidity is not null");
            return (Criteria) this;
        }

        public Criteria andHumidityEqualTo(String value) {
            addCriterion("humidity =", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotEqualTo(String value) {
            addCriterion("humidity <>", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThan(String value) {
            addCriterion("humidity >", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThanOrEqualTo(String value) {
            addCriterion("humidity >=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThan(String value) {
            addCriterion("humidity <", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThanOrEqualTo(String value) {
            addCriterion("humidity <=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLike(String value) {
            addCriterion("humidity like", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotLike(String value) {
            addCriterion("humidity not like", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityIn(List<String> values) {
            addCriterion("humidity in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotIn(List<String> values) {
            addCriterion("humidity not in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityBetween(String value1, String value2) {
            addCriterion("humidity between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotBetween(String value1, String value2) {
            addCriterion("humidity not between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_sk
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 02 11:46:25 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}