package com.nengliang.web.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeatherIdExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public WeatherIdExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andToday_faIsNull() {
            addCriterion("today_fa is null");
            return (Criteria) this;
        }

        public Criteria andToday_faIsNotNull() {
            addCriterion("today_fa is not null");
            return (Criteria) this;
        }

        public Criteria andToday_faEqualTo(String value) {
            addCriterion("today_fa =", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faNotEqualTo(String value) {
            addCriterion("today_fa <>", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faGreaterThan(String value) {
            addCriterion("today_fa >", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faGreaterThanOrEqualTo(String value) {
            addCriterion("today_fa >=", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faLessThan(String value) {
            addCriterion("today_fa <", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faLessThanOrEqualTo(String value) {
            addCriterion("today_fa <=", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faLike(String value) {
            addCriterion("today_fa like", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faNotLike(String value) {
            addCriterion("today_fa not like", value, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faIn(List<String> values) {
            addCriterion("today_fa in", values, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faNotIn(List<String> values) {
            addCriterion("today_fa not in", values, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faBetween(String value1, String value2) {
            addCriterion("today_fa between", value1, value2, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_faNotBetween(String value1, String value2) {
            addCriterion("today_fa not between", value1, value2, "today_fa");
            return (Criteria) this;
        }

        public Criteria andToday_fbIsNull() {
            addCriterion("today_fb is null");
            return (Criteria) this;
        }

        public Criteria andToday_fbIsNotNull() {
            addCriterion("today_fb is not null");
            return (Criteria) this;
        }

        public Criteria andToday_fbEqualTo(String value) {
            addCriterion("today_fb =", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbNotEqualTo(String value) {
            addCriterion("today_fb <>", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbGreaterThan(String value) {
            addCriterion("today_fb >", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbGreaterThanOrEqualTo(String value) {
            addCriterion("today_fb >=", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbLessThan(String value) {
            addCriterion("today_fb <", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbLessThanOrEqualTo(String value) {
            addCriterion("today_fb <=", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbLike(String value) {
            addCriterion("today_fb like", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbNotLike(String value) {
            addCriterion("today_fb not like", value, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbIn(List<String> values) {
            addCriterion("today_fb in", values, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbNotIn(List<String> values) {
            addCriterion("today_fb not in", values, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbBetween(String value1, String value2) {
            addCriterion("today_fb between", value1, value2, "today_fb");
            return (Criteria) this;
        }

        public Criteria andToday_fbNotBetween(String value1, String value2) {
            addCriterion("today_fb not between", value1, value2, "today_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_faIsNull() {
            addCriterion("future_fa is null");
            return (Criteria) this;
        }

        public Criteria andFuture_faIsNotNull() {
            addCriterion("future_fa is not null");
            return (Criteria) this;
        }

        public Criteria andFuture_faEqualTo(String value) {
            addCriterion("future_fa =", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faNotEqualTo(String value) {
            addCriterion("future_fa <>", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faGreaterThan(String value) {
            addCriterion("future_fa >", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faGreaterThanOrEqualTo(String value) {
            addCriterion("future_fa >=", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faLessThan(String value) {
            addCriterion("future_fa <", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faLessThanOrEqualTo(String value) {
            addCriterion("future_fa <=", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faLike(String value) {
            addCriterion("future_fa like", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faNotLike(String value) {
            addCriterion("future_fa not like", value, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faIn(List<String> values) {
            addCriterion("future_fa in", values, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faNotIn(List<String> values) {
            addCriterion("future_fa not in", values, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faBetween(String value1, String value2) {
            addCriterion("future_fa between", value1, value2, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_faNotBetween(String value1, String value2) {
            addCriterion("future_fa not between", value1, value2, "future_fa");
            return (Criteria) this;
        }

        public Criteria andFuture_fbIsNull() {
            addCriterion("future_fb is null");
            return (Criteria) this;
        }

        public Criteria andFuture_fbIsNotNull() {
            addCriterion("future_fb is not null");
            return (Criteria) this;
        }

        public Criteria andFuture_fbEqualTo(String value) {
            addCriterion("future_fb =", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbNotEqualTo(String value) {
            addCriterion("future_fb <>", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbGreaterThan(String value) {
            addCriterion("future_fb >", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbGreaterThanOrEqualTo(String value) {
            addCriterion("future_fb >=", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbLessThan(String value) {
            addCriterion("future_fb <", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbLessThanOrEqualTo(String value) {
            addCriterion("future_fb <=", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbLike(String value) {
            addCriterion("future_fb like", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbNotLike(String value) {
            addCriterion("future_fb not like", value, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbIn(List<String> values) {
            addCriterion("future_fb in", values, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbNotIn(List<String> values) {
            addCriterion("future_fb not in", values, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbBetween(String value1, String value2) {
            addCriterion("future_fb between", value1, value2, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFuture_fbNotBetween(String value1, String value2) {
            addCriterion("future_fb not between", value1, value2, "future_fb");
            return (Criteria) this;
        }

        public Criteria andFaIsNull() {
            addCriterion("fa is null");
            return (Criteria) this;
        }

        public Criteria andFaIsNotNull() {
            addCriterion("fa is not null");
            return (Criteria) this;
        }

        public Criteria andFaEqualTo(String value) {
            addCriterion("fa =", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaNotEqualTo(String value) {
            addCriterion("fa <>", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaGreaterThan(String value) {
            addCriterion("fa >", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaGreaterThanOrEqualTo(String value) {
            addCriterion("fa >=", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaLessThan(String value) {
            addCriterion("fa <", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaLessThanOrEqualTo(String value) {
            addCriterion("fa <=", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaLike(String value) {
            addCriterion("fa like", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaNotLike(String value) {
            addCriterion("fa not like", value, "fa");
            return (Criteria) this;
        }

        public Criteria andFaIn(List<String> values) {
            addCriterion("fa in", values, "fa");
            return (Criteria) this;
        }

        public Criteria andFaNotIn(List<String> values) {
            addCriterion("fa not in", values, "fa");
            return (Criteria) this;
        }

        public Criteria andFaBetween(String value1, String value2) {
            addCriterion("fa between", value1, value2, "fa");
            return (Criteria) this;
        }

        public Criteria andFaNotBetween(String value1, String value2) {
            addCriterion("fa not between", value1, value2, "fa");
            return (Criteria) this;
        }

        public Criteria andFbIsNull() {
            addCriterion("fb is null");
            return (Criteria) this;
        }

        public Criteria andFbIsNotNull() {
            addCriterion("fb is not null");
            return (Criteria) this;
        }

        public Criteria andFbEqualTo(String value) {
            addCriterion("fb =", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotEqualTo(String value) {
            addCriterion("fb <>", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbGreaterThan(String value) {
            addCriterion("fb >", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbGreaterThanOrEqualTo(String value) {
            addCriterion("fb >=", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbLessThan(String value) {
            addCriterion("fb <", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbLessThanOrEqualTo(String value) {
            addCriterion("fb <=", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbLike(String value) {
            addCriterion("fb like", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotLike(String value) {
            addCriterion("fb not like", value, "fb");
            return (Criteria) this;
        }

        public Criteria andFbIn(List<String> values) {
            addCriterion("fb in", values, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotIn(List<String> values) {
            addCriterion("fb not in", values, "fb");
            return (Criteria) this;
        }

        public Criteria andFbBetween(String value1, String value2) {
            addCriterion("fb between", value1, value2, "fb");
            return (Criteria) this;
        }

        public Criteria andFbNotBetween(String value1, String value2) {
            addCriterion("fb not between", value1, value2, "fb");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeEqualTo(Date value) {
            addCriterion("update_time =", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThan(Date value) {
            addCriterion("update_time >", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThan(Date value) {
            addCriterion("update_time <", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeIn(List<Date> values) {
            addCriterion("update_time in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "update_time");
            return (Criteria) this;
        }

        public Criteria andUpdate_timeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "update_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_id
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 02 19:47:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}