package com.nengliang.web.entity;

import java.util.Date;

public class WeatherToday {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.today_id
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private Integer today_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.city
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.date_y
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String date_y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.week
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.temperature
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.weather
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String weather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.wind
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String wind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.dressing_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String dressing_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.dressing_advice
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String dressing_advice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.uv_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String uv_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.comfort_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String comfort_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.wash_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String wash_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.travel_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String travel_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.exercise_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String exercise_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.drying_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String drying_index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_today.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.today_id
     *
     * @return the value of weather_today.today_id
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public Integer getToday_id() {
        return today_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.today_id
     *
     * @param today_id the value for weather_today.today_id
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setToday_id(Integer today_id) {
        this.today_id = today_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.city
     *
     * @return the value of weather_today.city
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.city
     *
     * @param city the value for weather_today.city
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.date_y
     *
     * @return the value of weather_today.date_y
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getDate_y() {
        return date_y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.date_y
     *
     * @param date_y the value for weather_today.date_y
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setDate_y(String date_y) {
        this.date_y = date_y == null ? null : date_y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.week
     *
     * @return the value of weather_today.week
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.week
     *
     * @param week the value for weather_today.week
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.temperature
     *
     * @return the value of weather_today.temperature
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.temperature
     *
     * @param temperature the value for weather_today.temperature
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.weather
     *
     * @return the value of weather_today.weather
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.weather
     *
     * @param weather the value for weather_today.weather
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.wind
     *
     * @return the value of weather_today.wind
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getWind() {
        return wind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.wind
     *
     * @param wind the value for weather_today.wind
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setWind(String wind) {
        this.wind = wind == null ? null : wind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.dressing_index
     *
     * @return the value of weather_today.dressing_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getDressing_index() {
        return dressing_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.dressing_index
     *
     * @param dressing_index the value for weather_today.dressing_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setDressing_index(String dressing_index) {
        this.dressing_index = dressing_index == null ? null : dressing_index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.dressing_advice
     *
     * @return the value of weather_today.dressing_advice
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getDressing_advice() {
        return dressing_advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.dressing_advice
     *
     * @param dressing_advice the value for weather_today.dressing_advice
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setDressing_advice(String dressing_advice) {
        this.dressing_advice = dressing_advice == null ? null : dressing_advice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.uv_index
     *
     * @return the value of weather_today.uv_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getUv_index() {
        return uv_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.uv_index
     *
     * @param uv_index the value for weather_today.uv_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setUv_index(String uv_index) {
        this.uv_index = uv_index == null ? null : uv_index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.comfort_index
     *
     * @return the value of weather_today.comfort_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getComfort_index() {
        return comfort_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.comfort_index
     *
     * @param comfort_index the value for weather_today.comfort_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setComfort_index(String comfort_index) {
        this.comfort_index = comfort_index == null ? null : comfort_index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.wash_index
     *
     * @return the value of weather_today.wash_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getWash_index() {
        return wash_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.wash_index
     *
     * @param wash_index the value for weather_today.wash_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setWash_index(String wash_index) {
        this.wash_index = wash_index == null ? null : wash_index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.travel_index
     *
     * @return the value of weather_today.travel_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getTravel_index() {
        return travel_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.travel_index
     *
     * @param travel_index the value for weather_today.travel_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setTravel_index(String travel_index) {
        this.travel_index = travel_index == null ? null : travel_index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.exercise_index
     *
     * @return the value of weather_today.exercise_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getExercise_index() {
        return exercise_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.exercise_index
     *
     * @param exercise_index the value for weather_today.exercise_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setExercise_index(String exercise_index) {
        this.exercise_index = exercise_index == null ? null : exercise_index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.drying_index
     *
     * @return the value of weather_today.drying_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getDrying_index() {
        return drying_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.drying_index
     *
     * @param drying_index the value for weather_today.drying_index
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setDrying_index(String drying_index) {
        this.drying_index = drying_index == null ? null : drying_index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.create_time
     *
     * @return the value of weather_today.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.create_time
     *
     * @param create_time the value for weather_today.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_today.update_time
     *
     * @return the value of weather_today.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_today.update_time
     *
     * @param update_time the value for weather_today.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}