package com.nengliang.web.entity;

import java.util.Date;

public class WeatherSk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.sk_id
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private Integer sk_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.temp
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private String temp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.wind_direction
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private String wind_direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.wind_strength
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private String wind_strength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.humidity
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private String humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_sk.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.sk_id
     *
     * @return the value of weather_sk.sk_id
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public Integer getSk_id() {
        return sk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.sk_id
     *
     * @param sk_id the value for weather_sk.sk_id
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setSk_id(Integer sk_id) {
        this.sk_id = sk_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.temp
     *
     * @return the value of weather_sk.temp
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public String getTemp() {
        return temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.temp
     *
     * @param temp the value for weather_sk.temp
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setTemp(String temp) {
        this.temp = temp == null ? null : temp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.wind_direction
     *
     * @return the value of weather_sk.wind_direction
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public String getWind_direction() {
        return wind_direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.wind_direction
     *
     * @param wind_direction the value for weather_sk.wind_direction
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setWind_direction(String wind_direction) {
        this.wind_direction = wind_direction == null ? null : wind_direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.wind_strength
     *
     * @return the value of weather_sk.wind_strength
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public String getWind_strength() {
        return wind_strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.wind_strength
     *
     * @param wind_strength the value for weather_sk.wind_strength
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setWind_strength(String wind_strength) {
        this.wind_strength = wind_strength == null ? null : wind_strength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.humidity
     *
     * @return the value of weather_sk.humidity
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public String getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.humidity
     *
     * @param humidity the value for weather_sk.humidity
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setHumidity(String humidity) {
        this.humidity = humidity == null ? null : humidity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.time
     *
     * @return the value of weather_sk.time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.time
     *
     * @param time the value for weather_sk.time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.create_time
     *
     * @return the value of weather_sk.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.create_time
     *
     * @param create_time the value for weather_sk.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_sk.update_time
     *
     * @return the value of weather_sk.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_sk.update_time
     *
     * @param update_time the value for weather_sk.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}