package com.nengliang.web.entity;

import java.util.Date;

public class WeatherFuture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.future_id
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private Integer future_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.temperature
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.weather
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String weather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.wind
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String wind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.week
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    private String week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.date
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_future.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.future_id
     *
     * @return the value of weather_future.future_id
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public Integer getFuture_id() {
        return future_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.future_id
     *
     * @param future_id the value for weather_future.future_id
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setFuture_id(Integer future_id) {
        this.future_id = future_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.temperature
     *
     * @return the value of weather_future.temperature
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.temperature
     *
     * @param temperature the value for weather_future.temperature
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.weather
     *
     * @return the value of weather_future.weather
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.weather
     *
     * @param weather the value for weather_future.weather
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.wind
     *
     * @return the value of weather_future.wind
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getWind() {
        return wind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.wind
     *
     * @param wind the value for weather_future.wind
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setWind(String wind) {
        this.wind = wind == null ? null : wind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.week
     *
     * @return the value of weather_future.week
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.week
     *
     * @param week the value for weather_future.week
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.date
     *
     * @return the value of weather_future.date
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.date
     *
     * @param date the value for weather_future.date
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.create_time
     *
     * @return the value of weather_future.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.create_time
     *
     * @param create_time the value for weather_future.create_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_future.update_time
     *
     * @return the value of weather_future.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_future.update_time
     *
     * @param update_time the value for weather_future.update_time
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}