package com.nengliang.web.dao;

import com.nengliang.web.entity.WeatherId;
import com.nengliang.web.entity.WeatherIdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeatherIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int countByExample(WeatherIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int deleteByExample(WeatherIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int insert(WeatherId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int insertSelective(WeatherId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    List<WeatherId> selectByExample(WeatherIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    WeatherId selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") WeatherId record, @Param("example") WeatherIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int updateByExample(@Param("record") WeatherId record, @Param("example") WeatherIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int updateByPrimaryKeySelective(WeatherId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_id
     *
     * @mbggenerated Mon Mar 02 19:47:47 CST 2020
     */
    int updateByPrimaryKey(WeatherId record);
}