package com.nengliang.web.dao;

import com.nengliang.web.entity.WeatherToday;
import com.nengliang.web.entity.WeatherTodayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeatherTodayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int countByExample(WeatherTodayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int deleteByExample(WeatherTodayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int deleteByPrimaryKey(Integer today_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int insert(WeatherToday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int insertSelective(WeatherToday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    List<WeatherToday> selectByExample(WeatherTodayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    WeatherToday selectByPrimaryKey(Integer today_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") WeatherToday record, @Param("example") WeatherTodayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int updateByExample(@Param("record") WeatherToday record, @Param("example") WeatherTodayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int updateByPrimaryKeySelective(WeatherToday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_today
     *
     * @mbggenerated Mon Mar 02 11:46:24 CST 2020
     */
    int updateByPrimaryKey(WeatherToday record);
}