package com.nengliang.web.dao;

import com.nengliang.web.entity.WeatherFuture;
import com.nengliang.web.entity.WeatherFutureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeatherFutureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int countByExample(WeatherFutureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int deleteByExample(WeatherFutureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int deleteByPrimaryKey(Integer future_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int insert(WeatherFuture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int insertSelective(WeatherFuture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    List<WeatherFuture> selectByExample(WeatherFutureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    WeatherFuture selectByPrimaryKey(Integer future_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") WeatherFuture record, @Param("example") WeatherFutureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByExample(@Param("record") WeatherFuture record, @Param("example") WeatherFutureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByPrimaryKeySelective(WeatherFuture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_future
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByPrimaryKey(WeatherFuture record);
}