package com.nengliang.web.dao;

import com.nengliang.web.entity.WeatherSk;
import com.nengliang.web.entity.WeatherSkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeatherSkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int countByExample(WeatherSkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int deleteByExample(WeatherSkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int deleteByPrimaryKey(Integer sk_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int insert(WeatherSk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int insertSelective(WeatherSk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    List<WeatherSk> selectByExample(WeatherSkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    WeatherSk selectByPrimaryKey(Integer sk_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") WeatherSk record, @Param("example") WeatherSkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByExample(@Param("record") WeatherSk record, @Param("example") WeatherSkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByPrimaryKeySelective(WeatherSk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_sk
     *
     * @mbggenerated Mon Mar 02 11:46:25 CST 2020
     */
    int updateByPrimaryKey(WeatherSk record);
}